### PR TITLE
Code review main charge system

### PR DESCRIPTION
**Pull request by buipp**
I am not sure what else needs to be added but it is at a descent stopping point

### CODE REVIEW

File: .vscode/test/test_maincharge.cpp
Comment (RCMast3r) [inline .vscode/test/test_maincharge.cpp:1]: wait wat, why is this here?

File: lib/constants/CCUParams.h [hunk 1]
```diff
@@ -0,0 +1,7 @@
+#include <Arduino.h>
+
+struct CCUParams{
+  double target_voltage = 3.1; //per cell
+  int max_AC_current = 15; //need to add the DC current setpoint probably 30 amps
+  float ideal_cell_temp = 40;
+};
```
Comment (RCMast3r) [inline lib/constants/CCUParams.h:7]: i would recommend using a namespace instead for this and make these const instead of a struct. 

what this means essentially is you can create an instance of CCUParams and these are the default values for CCUParams instance structs. we dont really ever need multiple instances of CCUParams floating around so we dont need to make a struct for them.

File: lib/constants/pidParams.h [hunk 2]
```diff
@@ -0,0 +1,8 @@
+#include <Arduino.h>
+
+struct PIDParams {
+  uint32_t PIDrunInterval = 12;
+  float Kp = 1;
+  float Ki = 1;
+  float Kd = 1;
+};
```
Comment (RCMast3r) [inline lib/constants/pidParams.h:8]: see comment about CCUParams struct

File: lib/interfaces/EthernetInterface.h [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+    float min_voltage;
+    float max_voltage;
+    size_t min_voltage_cell_id;              // 0 - 125
+    size_t max_voltage_cell_id;              // 0 - 125
+    size_t max_board_temperature_segment_id; // 0 - 5
+    size_t max_humidity_segment_id;          // 0 - 5
+    size_t max_cell_temperature_cell_id;     // 0 - 47
+    float total_voltage;
+    float average_cell_temperature;
+};
```
Comment (RCMast3r) [inline lib/interfaces/EthernetInterface.h:16]: pls dont push commented code. looks like this is just a copy-paste of what exists in the shared firmware types repo. you can just include a url link to the type instead

File: lib/interfaces/EthernetInterface.h [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+*/
+struct EthernetInterface
+{
+    float maxCellTemp = 70; //in degress C
+    float maxCellV = 2.3; //in Volts
+};
```
Comment (RCMast3r) [inline lib/interfaces/EthernetInterface.h:22]: what is this for? is this just the beginnings of the ethernet interface im assuming?

File: lib/constants/CCUParams.h
Comment (RCMast3r) [inline lib/constants/CCUParams.h:1]: typically we do not have a library dedicated to constants within firmware projects but its not the worst pattern. typically the systems are themselves configurable via their constructors and the args of the constructors are passed in on construction from a platformio project specific include (such as `MCU_rev15_defs.h`)

File: lib/systems/MainChargeSystem.h
Comment (RCMast3r) [inline lib/systems/MainChargeSystem.h:1]: please turn this into a proper class

File: lib/systems/MainChargeSystem.h [hunk 5]
```diff
@@ -1,43 +1,43 @@
...
+float current_setpoint;
 
-/* Function Init */
-
-int set_charge_current();
+/* Object Instance Creation */
+EthernetInterface ethernetInterface;
+CCUParams ccuParams;
+PID_RT pid;
+PIDParams pidParams;
```
Comment (RCMast3r) [inline lib/systems/MainChargeSystem.h:20]: dont just put variables in a header generally, this is a good way to get duplicate symbol errors and it is bad practice (generally speaking)

File: lib/systems/MainChargeSystem.h [hunk 6]
```diff
@@ -1,43 +1,43 @@
...
-      set_charge_current(); //sets the charge current to the PID adjusted value
-      current_flow = true; //same as line 32
+    pid.compute(ethernetInterface.maxCellTemp-ccuParams.ideal_cell_temp); //also probably account to voltage
+    float pidTemp = pid.getOutput();
+    pid.compute(ethernetInterface.maxCellV-ccuParams.target_voltage);
+    float pidVolts = pid.getOutput();
+    float scalar = min(pidTemp, pidVolts);
+    current_setpoint = ccuParams.max_AC_current * scalar; //replace with just a Pd
+    current_flow = true; //same as line 32
   }
```
Comment (RCMast3r) [inline lib/systems/MainChargeSystem.h:42]: please put this functionality into a class and not just an anonymous function that affects random global variables. also please prefer functions that take args (if input is needed) and return the results of some computation to be more functional instead of stateful (stateful is what you are doing here)

**Review by RCMast3r — CHANGES_REQUESTED** [review]

File: .vscode/test/test_maincharge.cpp
Comment (buipp) [reply .vscode/test/test_maincharge.cpp:1]: I realized it was in the wrong spot right before you posted this and forgot to push the changes. Will be pushed out with some unit tests soon

File: lib/interfaces/EthernetInterface.h (hunk 4 above)
Comment (buipp) [reply lib/interfaces/EthernetInterface.h:22]: This is just placeholder values for what the ethernet interface will return, I was using it as input into my unit tests but I think now I will be setting those values within the actual tests.

File: lib/constants/CCUParams.h
Comment (jhwang04) [reply lib/constants/CCUParams.h:1]: Yeah. Perhaps this constants file would be better suited as a .h and .cpp file in the main src/include folder?

File: lib/constants/pidParams.h [hunk 7]
```diff
@@ -0,0 +1,10 @@
+#ifndef __PIDPARAMS_H__
+#define __PIDPARAMS_H__
+
+//A centralized place to tune the PID
+namespace PidParams {
+  const float Kp = 1;
+  const float Ki = 1;
+  const float Kd = 1;
+};
+#endif
```
Comment (jhwang04) [inline lib/constants/pidParams.h:10]: What do these represent? Are these the specific PID params for a particular PID controller, or is this is a generic struct that can be used whenever you need to pass some PID params somewhere?
If these are specific, then name them as such (ChargeControllerPIDParams or something fitting)
If these are not specific, then make it a struct with the default values 0, 0, 0 (so no error correction).

File: lib/interfaces/include/EthernetInterface.h [hunk 8]
```diff
@@ -0,0 +1,30 @@
...
+
+class EthernetInterface{
+public:
+    EthernetInterface();
+    CCUInputValues UpdatingValues();
+
+private:
+    CCUInputValues inputValues;
+};
+#endif
```
Comment (jhwang04) [inline lib/interfaces/include/EthernetInterface.h:30]: I'd rewrite your ethernet interface to follow a similar paradigm as VCR. You have your real struct that you care about, your protoc struct, and your incoming bitstream. You can look at ProtobufMsgInterface.h in shared_firmware_interfaces to parse the bitstream into protoc struct, then your  ethernet interface should just be taking protoc struct and mapping those values to a struct you care about.

File: lib/systems/include/MainChargeSystem.h [hunk 9]
```diff
@@ -0,0 +1,18 @@
+#ifndef __MAINCHARGE_H__
+#define __MAINCHARGE_H__
+
+
+#include "CCUPID.h"
+#include "EthernetInterface.h"
+#include "CCUParams.h"
+
+
```
Comment (jhwang04) [inline lib/systems/include/MainChargeSystem.h:9]: Before starting to write code, make sure you're very clear on _what_  this class is responsible for doing. With any object oriented design (OOD), you need to define a few things:
- what does this class *have*
- what does this class *do*

from those, you can define
- what does this class *need* in order to *do* those things

then, and only then, should you start writing code.

File: lib/systems/src/MainChargeSystem.cpp [hunk 10]
```diff
@@ -0,0 +1,28 @@
+/* Imports */
+#include "MainChargeSystem.h"
+
+namespace calc {
```
Comment (jhwang04) [inline lib/systems/src/MainChargeSystem.cpp:4]: calc is a pretty generic name. I know I tend to be overly nitpicky about names, but especially when lots and lots of people will be reading and studying this code, it's extremely important for names to be descriptive and self-explanatory. What are you calculating, and how will this namespace be used?

**Review by jhwang04 — CHANGES_REQUESTED** [review]

File: lib/interfaces/src/EthernetInterface.cpp
Comment (RCMast3r) [inline lib/interfaces/src/EthernetInterface.cpp:1]: see comment from justin about ethernet interface

File: lib/systems/src/MainChargeSystem.cpp [hunk 11]
```diff
@@ -0,0 +1,28 @@
...
+  float min(float v1, float v2){
```
Comment (RCMast3r) [inline lib/systems/src/MainChargeSystem.cpp:5]: pls use `std::min`:

https://en.cppreference.com/w/cpp/algorithm/min

File: lib/systems/src/MainChargeSystem.cpp [hunk 12]
```diff
@@ -0,0 +1,28 @@
...
+          return v1;
+      }
+      else{
+          return v2;
+      }
+  };
+};
+
+void MainChargeSystem::charge_cycle(CCUInputValues inputValues, CCUOutputValues &outputValues){
+    if (inputValues.maxCellV >= CCUParams::target_voltage || inputValues.maxCellTemp > CCUParams::ideal_cell_temp) { //checks whether or not any of the cells are charged yet
```
Comment (RCMast3r) [inline lib/systems/src/MainChargeSystem.cpp:17]: please propagate the parameters through the member variables so that on construction of the charger we can control what the parameters are. see here: https://github.com/hytech-racing/VCR/blob/main/lib/systems/include/TorqueControllerMux.hpp#L82

as an example of how to do so

File: lib/systems/src/MainChargeSystem.cpp [hunk 13]
```diff
@@ -0,0 +1,28 @@
...
+      outputValues.currentFlow = false; //this will be function that actually turns on/off current flow 
+      outputValues.current_setpoint = 0;
+    }
+    else { 
+      float pidTemp = pid.compute(CCUParams::ideal_cell_temp, inputValues.maxCellTemp); 
+      float pidVolts = pid.compute(CCUParams::target_voltage, inputValues.maxCellV);
```
Comment (RCMast3r) [inline lib/systems/src/MainChargeSystem.cpp:23]: see comment about parameter specification

File: lib/systems/src/MainChargeSystem.cpp [hunk 14]
```diff
@@ -0,0 +1,28 @@
...
+      float scalar = calc::min(pidTemp, pidVolts);
```
Comment (RCMast3r) [inline lib/systems/src/MainChargeSystem.cpp:24]: std::min pls

File: lib/utilities/CCUPID.h [hunk 15]
```diff
@@ -0,0 +1,33 @@
...
+    
+    float compute(double setpoint, double measured_value) {
+        float error = setpoint - measured_value;
+        integral += error;
+        float derivative = error - prev_error;
+        prev_error = error;
+        return (Kp * error) + (Ki * integral) + (Kd * derivative);
+    }
+
+    void setTunings(double kp, double ki, double kd) {
```
Comment (RCMast3r) [inline lib/utilities/CCUPID.h:20]: please be consistent with styling use in most places on firmware. `snake_case` for functions, `CamelCase` for objects / classes.

File: lib/systems/src/MainChargeSystem.cpp (hunk 13 above)
Comment (RCMast3r) [inline lib/systems/src/MainChargeSystem.cpp:23]: wait why do we have two pids? these PID controllers are not being used correctly either. 

1. we are not going to PID the temp to some ideal temp. we will simply bang-bang control the charger once we reach above 45 deg C: (charger turns off at 45C, charger turns back on once max cell temp has reached 40C)

2. The ideal charge current curve will be a function of the actual battery pack state of charge that needs to be estimated.  

3. the charge current should taper off once we are getting closer to full pack, not increase as we get closer to our max cell voltage like what we are attempting to do here with the PID.

4. I think what would be more appropriate for us would be a simple logarithmic function for determining our charge current setup such that our charge current decreases as we get closer to full pack state of charge.

5. additionally, the charge control needs to be able to be shutoff by the ACU when the ACU detects that balancing needs to occur due to a max-min cell voltage difference occurring and / or all the other reasons that we will need. 

Also we can actually charge at ~13A continuous according to the cell data sheet, but we prob want to start with ~80% of that as our max. see the ACU firmware requirements wiki page for details

**Review by RCMast3r — CHANGES_REQUESTED** [review]

**Comment by buipp** [comment]
Class constructor has been parameterized, removed the PID to make the math simpler, Ethernet interface has not been touched since the last review so no need to review it.

File: lib/interfaces/include/EthernetInterface.h [hunk 16]
```diff
@@ -0,0 +1,30 @@
...
+
+struct CCUOutput_s
+//Output values struct (what CCU is sending out)
+{
+    bool current_flow;
+    float current_setpoint;
+    bool allow_balance;
+};
+
+namespace ethernetInterface{
```
Comment (jhwang04) [inline lib/interfaces/include/EthernetInterface.h:26]: follow naming conventions

File: lib/interfaces/src/EthernetInterface.cpp [hunk 17]
```diff
@@ -0,0 +1,18 @@
...
+
+//take the values from the protobuf message and update CCUInput_s 
+
+void ethernetInterface::recieve_pb_msg_acu_all_data(hytech_msgs_ACUAllData_s &msg_in, CCUInput_s &inputValues){
+
+    inputValues.max_cell_voltage = *std::max_element(msg_in.voltages, msg_in.voltages + msg_in.voltages_count);
+
+    inputValues.max_cell_temperature = *std::max_element(msg_in.cell_temperatures, msg_in.cell_temperatures + msg_in.cell_temperatures_count);
+
+}
```
Comment (jhwang04) [inline lib/interfaces/src/EthernetInterface.cpp:18]: this will be rewritten with Mai :)

File: lib/systems/include/MainChargeSystem.h [hunk 18]
```diff
@@ -0,0 +1,40 @@
...
+#define __MAINCHARGE_H__
+
+
+#include "EthernetInterface.h"
+
+
+/**
+ * MainChargeSystem has its own PID object for adjusting error
+ * It needs to have a function that is a one loop of charging where CCU gets info about the cells, calculates correct current,
+ * and sends out current set and whether to enable charging or not.
```
Comment (jhwang04) [inline lib/systems/include/MainChargeSystem.h:11]: What is current set? Is that the current setpoint? Does current mean "right now", or electrical current?

iirc, MainChargeSystem is just responsible for determining the electrical current to charge at. If charging should not be enabled, MainChargeSystem can simply return 0.

File: lib/systems/include/MainChargeSystem.h [hunk 19]
```diff
@@ -0,0 +1,40 @@
...
+  public:
+    /**
+     * @param target_volt The wanted final voltage for an individual cell
+     * @param max_charge_current The maximum charge current that should be given to ACU
+     * @param max_cell_temp The maximum allowable cell temperature while charging
+     * @param pid_kp The Kp parameter for the PID that controls charging current with respect to how close the max cell is to the target voltage
+     * @param pid_ki The Ki parameter for the PID that controls charging current with respect to how close the max cell is to the target voltage
+     * @param pid_kd The Kd parameter for the PID that controls charging current with respect to how close the max cell is to the target voltage
+     */
+    MainChargeSystem(float target_volt, float max_charge_current, float max_cell_temp);
```
Comment (jhwang04) [inline lib/systems/include/MainChargeSystem.h:23]: I don't think you should necessarily need a full PID for this, a simple P-controller should be sufficient.

File: lib/systems/include/MainChargeSystem.h [hunk 20]
```diff
@@ -0,0 +1,40 @@
...
+*/
+class MainChargeSystem {
+  public:
+    /**
+     * @param target_volt The wanted final voltage for an individual cell
+     * @param max_charge_current The maximum charge current that should be given to ACU
+     * @param max_cell_temp The maximum allowable cell temperature while charging
+     * @param pid_kp The Kp parameter for the PID that controls charging current with respect to how close the max cell is to the target voltage
+     * @param pid_ki The Ki parameter for the PID that controls charging current with respect to how close the max cell is to the target voltage
+     * @param pid_kd The Kd parameter for the PID that controls charging current with respect to how close the max cell is to the target voltage
```
Comment (jhwang04) [inline lib/systems/include/MainChargeSystem.h:21]: You should be constantly-updating your documentation comments to match the behavior of the code

File: lib/systems/include/MainChargeSystem.h [hunk 21]
```diff
@@ -0,0 +1,40 @@
...
+     */
+    MainChargeSystem(float target_volt, float max_charge_current, float max_cell_temp);
+    /**
+     * @param CCUInput_s The incoming struct from ACU
+     * @param CCUOutput_s The output struct from CCU with charge current and whether to enable charging
+     */
+    void charge_cycle(CCUInput_s inputValues, CCUOutput_s& outputValues); //need to add safe start that ramps up to max over 10 seconds
```
Comment (jhwang04) [inline lib/systems/include/MainChargeSystem.h:28]: Is there a reason you're passing in a struct to use as an output instead of simply returning an instance of CCUOutput_s?

Also, what's in CCUOutput_s? What does CCU need to return other than the charge current?

File: lib/systems/src/MainChargeSystem.cpp [hunk 22]
```diff
@@ -0,0 +1,21 @@
...
+
+void MainChargeSystem::charge_cycle(CCUInput_s inputValues, CCUOutput_s &outputValues){
+    if (inputValues.max_cell_voltage >= target_voltage || inputValues.max_cell_temperature > max_allowable_cell_temperature) { //checks whether or not any of the cells are charged yet
+      outputValues.current_flow = false; //this will be function that actually turns on/off current flow 
+      outputValues.current_setpoint = 0;
+    }
+    else { 
+      float temperature_scalar = ((max_allowable_cell_temperature - inputValues.max_cell_temperature)/10); //This needs to be replaces with a log function  
+      float distance_from_ideal_voltage = target_voltage - inputValues.max_cell_voltage;
+      float voltage_scalar = ((log(distance_from_ideal_voltage+.5))/log(11))+.3;
```
Comment (jhwang04) [inline lib/systems/src/MainChargeSystem.cpp:16]: Where does this math come from?

File: platformio.ini [hunk 23]
```diff
@@ -1,65 +1,57 @@
-; Hytech CCU PlatformIO configuration file.
+; PlatformIO Project Configuration File
+;
+;   Build options: build flags, source filter
+;   Upload options: custom upload port, speed and extra flags
+;   Library options: dependencies, extra library storages
+;   Advanced options: extra scripting
 ;
 ; Please visit documentation for the other options and examples
 ; https://docs.platformio.org/page/projectconf.html
```
Comment (jhwang04) [inline platformio.ini:9]: You can delete the default PlatformIO comment header

File: src/include/CCUParams.h [hunk 24]
```diff
@@ -0,0 +1,10 @@
+#ifndef __CCUPARAMS_H__
+#define __CCUPARAMS_H__
+
+//This is a namespace that contains all of the future knob settable constants for CCu
+namespace CCUParams{
```
Comment (jhwang04) [inline src/include/CCUParams.h:5]: space after params before {

File: src/include/pidParams.h [hunk 25]
```diff
@@ -0,0 +1,11 @@
...
+#define __PIDPARAMS_H__
+
+//A centralized place to tune the PID
+namespace CCUPidParams {
+  const float Kp = 1;
+  const float Ki = 1;
+  const float Kd = 1;
+};
+
+#endif
```
Comment (jhwang04) [inline src/include/pidParams.h:11]: remove for now. if you need PID later, you may re-add

File: src/main.cpp [hunk 26]
```diff
@@ -1,8 +1,7 @@
 /* Libraries */
 #include <Arduino.h>
-#include "MainCharge_sys.h"
 #include <QNEthernet.h>
-
+#include "MainChargeSystem.h"
 /* Parameters */
 bool charge_enable = false;
```
Comment (jhwang04) [inline src/main.cpp:6]: shouldn't need this

File: src/main.cpp [hunk 27]
```diff
@@ -11,13 +10,13 @@ namespace qn = qindesign::network; //setup of qn namespace
...
 
 void setup() {
   //Serial.begin(115200); //I dont know if this is the baudrate I also don't know if this is even needed
   qn::Ethernet.begin(); //begins QNEthernet
+  
 }
 
 void loop() {
-  charge_cycle();
 }
```
Comment (jhwang04) [inline src/main.cpp:22]: Your main should be:
1) Initializing a charging system
2) Initializing Tasks (see HT_SCHED implementation in VCF)
3) Beginning serial if necessary
4) Initializing an instance of Scheduler
5) Calling Scheduler.run() in loop

**Review by jhwang04 — CHANGES_REQUESTED** [review]

File: lib/systems/include/MainChargeSystem.h (hunk 21 above)
Comment (buipp) [reply lib/systems/include/MainChargeSystem.h:28]: I thought that having a lot of instances was bad so I tried to make it work by changing a single instance. 

CCUOutput_s includes the charge current, whether or not balancing is allowed, and currently whether charging is enabled or not but I don't think that one is needed anymore

File: lib/systems/src/MainChargeSystem.cpp (hunk 22 above)
Comment (buipp) [reply lib/systems/src/MainChargeSystem.cpp:16]: Ben explained that a PID is stupid and over complicating things, he suggested using a logarithmic function instead. I made one that moves between 0 and 1 depending on the difference between the max cell voltage and ideal cell voltage when charged (assuming that the max difference will be 4 volts).

File: lib/systems/include/MainChargeSystem.h (hunk 18 above)
Comment (buipp) [reply lib/systems/include/MainChargeSystem.h:11]: old comment, has now been removed. You are correct that when charging should not be enabled MainChargeSystem should return 0.
